### ISSUE TITLE
Image comparison leads to exception

### ISSUE THREAD

**Issue by hevrard** [google/graphicsfuzz#290]
When going through the walkthrough, we hit an issue every time an image comparison is tried:

```
09:53:17 ERROR t:                        WorkQueue - Throwable
java.lang.RuntimeException: Command threw Throwable
	at com.graphicsfuzz.server.CommandRunnable.run(CommandRunnable.java:66) ~[fuzzerserver-1.0.jar:?]
	at com.graphicsfuzz.server.WorkQueue$MyWorker.run(WorkQueue.java:88) [fuzzerserver-1.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171-google-v7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171-google-v7]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171-google-v7]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171-google-v7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171-google-v7]
Caused by: java.lang.NoSuchMethodError: org.bytedeco.javacpp.opencv_core$MatVector.push_back(Lorg/bytedeco/javacpp/opencv_core$Mat;)Lorg/bytedeco/javacpp/opencv_core$MatVector;
	at com.graphicsfuzz.common.util.ImageUtil.getHistogram(ImageUtil.java:82) ~[common-1.0.jar:?]
	at com.graphicsfuzz.common.util.ShaderJobFileOperations$ImageData.<init>(ShaderJobFileOperations.java:1265) ~[common-1.0.jar:?]
	at com.graphicsfuzz.common.util.ShaderJobFileOperations.writeShaderResultToFileHelper(ShaderJobFileOperations.java:1238) ~[common-1.0.jar:?]
	at com.graphicsfuzz.common.util.ShaderJobFileOperations.writeShaderResultToFile(ShaderJobFileOperations.java:766) ~[common-1.0.jar:?]
	at com.graphicsfuzz.shadersets.RunShaderFamily.runShader(RunShaderFamily.java:228) ~[common-1.0.jar:?]
	at com.graphicsfuzz.shadersets.RunShaderFamily.runShaderFamily(RunShaderFamily.java:179) ~[common-1.0.jar:?]
	at com.graphicsfuzz.shadersets.RunShaderFamily.mainHelper(RunShaderFamily.java:133) ~[common-1.0.jar:?]
	at com.graphicsfuzz.server.GraphicsFuzzServerCommandDispatcher.dispatchCommand(GraphicsFuzzServerCommandDispatcher.java:37) ~[server-1.0.jar:?]
	at com.graphicsfuzz.server.CommandRunnable.run(CommandRunnable.java:63) ~[fuzzerserver-1.0.jar:?]
```

**Comment by paulthomson** [comment]
I can't repro this.

**Comment by afd** [comment]
@hevrard Would you be able to try this out again, perhaps tomorrow, and update or close the issue?
