### ISSUE TITLE
gles-worker desktop on Mac error version '100' is not supported

### ISSUE THREAD

**Issue by jiradeto** [google/graphicsfuzz#391]
**Environment**

- os.name: Mac OS X
- os.version: 10.13.4
- GL_VERSION : 2.1 INTEL-10.32.48
- GL_SHADING_LANGUAGE_VERSION: 1.20
- GL_VENDOR: Intel Inc
- GL_RENDERER: Intel Iris OpenGL Engine
- Java version: 1.8.0_191
- Python version: 3.7.2

**Description**

I executed command `java -ea -jar gles-worker-desktop.jar` to start the desktop glsl worker but it seems that shader does not compile and throws the following error log:

```Java
Main: SANITY_INIT_PREPARE
Main: SANITY_INIT_PREPARE
Main: Compiling shader.
Main: Compilation Time, in microsec: 1677
Main: Compiling shader.
Main: Compilation Time, in microsec: 1677
Main: Exception
com.graphicsfuzz.glesworker.PrepareShaderException: Vertex shader
ERROR: 0:1: '' :  version '100' is not supported
Fragment shader:
ERROR: 0:1: '' :  version '100' is not supported

Main: Exception
	at com.graphicsfuzz.glesworker.Main.prepareProgram(Main.java:587)
	at com.graphicsfuzz.glesworker.Main.render(Main.java:738)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.graphicsfuzz.glesworker.desktop.DesktopLauncher.start(DesktopLauncher.java:263)
	at com.graphicsfuzz.glesworker.desktop.DesktopLauncher.main(DesktopLauncher.java:164)
com.graphicsfuzz.glesworker.PrepareShaderException: Vertex shader
ERROR: 0:1: '' :  version '100' is not supported
Fragment shader:
ERROR: 0:1: '' :  version '100' is not supported

	at com.graphicsfuzz.glesworker.Main.prepareProgram(Main.java:587)
	at com.graphicsfuzz.glesworker.Main.render(Main.java:738)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:392)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:137)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:111)
	at com.graphicsfuzz.glesworker.desktop.DesktopLauncher.start(DesktopLauncher.java:263)
	at com.graphicsfuzz.glesworker.desktop.DesktopLauncher.main(DesktopLauncher.java:164)
Our DesktopWatchdog was instructed to exit process.

Process finished with exit code 1

```

**Comment by DanilDelegator** [comment]
I'm also running into this problem. Did you find a way to solve it?
