### ISSUE TITLE
glsl-to-spv-worker: error open_helper() when running with --local-shader-job

### ISSUE THREAD

**Issue by jiradeto** [google/graphicsfuzz#530]
Currently, when running single shader job with command ` glsl-to-spv-worker  --local-shader-job my_shader.json  my-worker host`, the worker throws an error: 

```python
Traceback (most recent call last):
  File "/Workspaces/graphicsfuzz/graphicsfuzz/target/graphicsfuzz/python/drivers/glsl-to-spv-worker.py", line 633, in <module>
    main()
  File "/Workspaces/graphicsfuzz/graphicsfuzz/target/graphicsfuzz/python/drivers/glsl-to-spv-worker.py", line 565, in main
    with runspv.open_helper(args.local_shader_job) as f:
TypeError: open_helper() missing 1 required positional argument: 'mode'
```

**Comment by jiradeto** [comment]
Fixed by #593.
