### ISSUE TITLE
Generate: AssertionError: null: com.graphicsfuzz.common.typing.Typer.visitArrayIndexExpr(Typer.java:503)

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#559]
To reproduce:

`graphicsfuzz-tool com.graphicsfuzz.generator.tool.Generate crash_generate/shader.json donors 100 variant.json --generate-uniform-bindings --max-uniforms 10 --seed=-173811911`

[AssertionError.zip](https://github.com/google/graphicsfuzz/files/3294123/AssertionError.zip)

<details>
 <summary>Stacktrace:</summary>

```
$ graphicsfuzz-tool com.graphicsfuzz.generator.tool.Generate crash_generate/shader.json donors 100 variant.json --generate-uniform-bindings --max-uniforms 10 --seed=-173811911
/data/git/graphicsfuzz/graphicsfuzz/target/graphicsfuzz/jar/tool-1.0.jar
['java', '-ea', '-cp', '/data/git/graphicsfuzz/graphicsfuzz/target/graphicsfuzz/jar/tool-1.0.jar', 'com.graphicsfuzz.generator.tool.Generate', 'crash_generate/shader.json', 'donors', '100', 'variant.json', '--generate-uniform-bindings', '--max-uniforms', '10', '--seed=-173811911']
13:59:01.222 INFO  ExecHelper - /data/git/graphicsfuzz/graphicsfuzz/target/graphicsfuzz/bin/Linux/glslangValidator -E --stdin -S frag
13:59:01.281 INFO  ExecHelper - Result: 0
13:59:01.648 ERROR Generate - 
java.lang.AssertionError: null
	at com.graphicsfuzz.common.typing.Typer.visitArrayIndexExpr(Typer.java:503) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ArrayIndexExpr.accept(ArrayIndexExpr.java:53) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitTypeConstructorExpr(StandardVisitor.java:235) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitTypeConstructorExpr(Typer.java:182) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.TypeConstructorExpr.accept(TypeConstructorExpr.java:86) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitBinaryExpr(StandardVisitor.java:178) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitBinaryExpr(Typer.java:302) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.BinaryExpr.accept(BinaryExpr.java:65) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitParenExpr(StandardVisitor.java:183) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitParenExpr(Typer.java:83) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ParenExpr.accept(ParenExpr.java:36) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitArrayIndexExpr(StandardVisitor.java:325) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitArrayIndexExpr(Typer.java:491) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ArrayIndexExpr.accept(ArrayIndexExpr.java:53) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitParenExpr(StandardVisitor.java:183) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitParenExpr(Typer.java:83) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ParenExpr.accept(ParenExpr.java:36) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitBinaryExpr(StandardVisitor.java:177) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitBinaryExpr(Typer.java:302) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.BinaryExpr.accept(BinaryExpr.java:65) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitTypeConstructorExpr(StandardVisitor.java:235) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitTypeConstructorExpr(Typer.java:182) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.TypeConstructorExpr.accept(TypeConstructorExpr.java:86) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitParenExpr(StandardVisitor.java:183) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitParenExpr(Typer.java:83) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ParenExpr.accept(ParenExpr.java:36) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitBinaryExpr(StandardVisitor.java:177) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitBinaryExpr(Typer.java:302) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.BinaryExpr.accept(BinaryExpr.java:65) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitArrayIndexExpr(StandardVisitor.java:325) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitArrayIndexExpr(Typer.java:491) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ArrayIndexExpr.accept(ArrayIndexExpr.java:53) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitTypeConstructorExpr(StandardVisitor.java:235) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitTypeConstructorExpr(Typer.java:182) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.TypeConstructorExpr.accept(TypeConstructorExpr.java:86) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitTernaryExpr(StandardVisitor.java:296) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitTernaryExpr(Typer.java:288) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.TernaryExpr.accept(TernaryExpr.java:54) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitParenExpr(StandardVisitor.java:183) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitParenExpr(Typer.java:83) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.ParenExpr.accept(ParenExpr.java:36) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitFunctionCallExpr(StandardVisitor.java:222) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionCallExpr(Typer.java:112) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.FunctionCallExpr.accept(FunctionCallExpr.java:73) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitMemberLookupExpr(StandardVisitor.java:197) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitMemberLookupExpr(Typer.java:394) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.MemberLookupExpr.accept(MemberLookupExpr.java:53) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitBinaryExpr(StandardVisitor.java:177) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitBinaryExpr(Typer.java:302) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.BinaryExpr.accept(BinaryExpr.java:65) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitBinaryExpr(StandardVisitor.java:178) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitBinaryExpr(Typer.java:302) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.expr.BinaryExpr.accept(BinaryExpr.java:65) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitIfStmt(StandardVisitor.java:138) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.stmt.IfStmt.accept(IfStmt.java:65) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:419) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitBlockStmt(StandardVisitor.java:132) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.ScopeTreeBuilder.visitBlockStmt(ScopeTreeBuilder.java:67) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.stmt.BlockStmt.accept(BlockStmt.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.ScopeTreeBuilder.visitFunctionDefinition(ScopeTreeBuilder.java:140) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.visitFunctionDefinition(Typer.java:102) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.decl.FunctionDefinition.accept(FunctionDefinition.java:42) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:415) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitTranslationUnit(StandardVisitor.java:113) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.TranslationUnit.accept(TranslationUnit.java:123) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:98) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.common.typing.Typer.<init>(Typer.java:74) ~[ast-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.canTypeCheckWithoutFailure(Generate.java:456) ~[generator-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.applyTransformationsMultiPass(Generate.java:438) ~[generator-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.transformShader(Generate.java:291) ~[generator-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.generateVariant(Generate.java:184) ~[generator-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.generateVariant(Generate.java:233) ~[generator-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.mainHelper(Generate.java:333) ~[generator-1.0.jar:?]
	at com.graphicsfuzz.generator.tool.Generate.main(Generate.java:313) [generator-1.0.jar:?]
```

</details>

**Comment by afd** [comment]
Fixed via #600
