### ISSUE TITLE
gfauto_fuzz terminated when a device was lost

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#696]
During fuzzing and Android device was lost.  This led to gfauto failing:

adb: error: failed to get feature set: device ... not found

Traceback (most recent call last):
  File "/data/graphicsfuzz/gfauto/.venv/bin/gfauto_fuzz", line 11, in <module>
    load_entry_point('gfauto', 'console_scripts', 'gfauto_fuzz')()
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz.py", line 155, in main
    main_helper(settings_path, iteration_seed)
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz.py", line 263, in main_helper
    binary_manager,
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz_glsl_test.py", line 72, in fuzz_glsl
    if handle_test(test_dir, reports_dir, active_devices, binary_manager, settings):
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz_glsl_test.py", line 302, in handle_test
    status = run(test_dir, binary_manager, device)
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz_glsl_test.py", line 187, in run
    binary_manager=binary_manager,
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz_glsl_test.py", line 421, in run_shader_job
    serial=device.android.serial,
  File "/data/graphicsfuzz/gfauto/gfauto/android_device.py", line 207, in run_amber_on_device
    serial,
  File "/data/graphicsfuzz/gfauto/gfauto/android_device.py", line 267, in run_amber_on_device_helper
    ["pull", ANDROID_DEVICE_RESULT_DIR + "/.", str(output_dir)],
  File "/data/graphicsfuzz/gfauto/gfauto/android_device.py", line 81, in adb_check
    return adb_helper(serial, adb_args, check_exit_code=True, verbose=verbose)
  File "/data/graphicsfuzz/gfauto/gfauto/android_device.py", line 73, in adb_helper
    verbose=verbose,
  File "/data/graphicsfuzz/gfauto/gfauto/subprocess_util.py", line 158, in run
    raise ex
  File "/data/graphicsfuzz/gfauto/gfauto/subprocess_util.py", line 148, in run
    result = run_helper(cmd, check_exit_code, timeout, env)
  File "/data/graphicsfuzz/gfauto/gfauto/subprocess_util.py", line 135, in run_helper
    raise subprocess.CalledProcessError(exit_code, process.args, stdout, stderr)
...

**Comment by paulthomson** [comment]
Fixed by #747

**Comment by paulthomson** [comment]
Not fixed yet! Doing "adb shell settings" can fail if the device has recently booted.

**Comment by paulthomson** [comment]
Fixed by #757
