### ISSUE TITLE
Reducer throws exception due to ExprCaseLabel not supporting child querying

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#697]
Here's the stack trace.  Attached file was the last successful shader.
[toupload.zip](https://github.com/google/graphicsfuzz/files/3510461/toupload.zip)

17:56:30.064 INFO  SystematicReductionPassManager - About to apply pass stmt: granularity: 55, index: 55
17:56:30.066 INFO  SystematicReductionPassManager - Pass stmt did not make a reduction step.
17:56:30.066 INFO  SystematicReductionPassManager - About to apply pass function: uninitialized
17:56:30.068 INFO  SystematicReductionPassManager - Pass function did not make a reduction step.
17:56:30.068 INFO  SystematicReductionPassManager - About to apply pass exprToConstant: uninitialized
java.lang.UnsupportedOperationException: Child querying not supported for nodes of type class com.graphicsfuzz.common.ast.stmt.ExprCaseLabel
	at com.graphicsfuzz.common.ast.IAstNode.hasChild(IAstNode.java:60)
	at com.graphicsfuzz.reducer.reductionopportunities.SimplifyExprReductionOpportunity.preconditionHolds(SimplifyExprReductionOpportunity.java:57)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.addOpportunity(ReductionOpportunitiesBase.java:258)
	at com.graphicsfuzz.reducer.reductionopportunities.ExprToConstantReductionOpportunities.identifyReductionOpportunitiesForChild(ExprToConstantReductionOpportunities.java:40)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitChildFromParent(ReductionOpportunitiesBase.java:201)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitExprCaseLabel(StandardVisitor.java:373)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitExprCaseLabel(ReductionOpportunitiesBase.java:97)
	at com.graphicsfuzz.common.ast.stmt.ExprCaseLabel.accept(ExprCaseLabel.java:49)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitBlockStmt(ReductionOpportunitiesBase.java:119)
	at com.graphicsfuzz.common.ast.stmt.BlockStmt.accept(BlockStmt.java:108)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:409)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:413)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitChildFromParent(ReductionOpportunitiesBase.java:199)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitSwitchStmt(StandardVisitor.java:364)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitSwitchStmt(ReductionOpportunitiesBase.java:91)
	at com.graphicsfuzz.common.ast.stmt.SwitchStmt.accept(SwitchStmt.java:59)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitBlockStmt(ReductionOpportunitiesBase.java:119)
	at com.graphicsfuzz.common.ast.stmt.BlockStmt.accept(BlockStmt.java:108)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitIfStmt(ReductionOpportunitiesBase.java:189)
	at com.graphicsfuzz.common.ast.stmt.IfStmt.accept(IfStmt.java:65)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitBlockStmt(ReductionOpportunitiesBase.java:119)
	at com.graphicsfuzz.common.ast.stmt.BlockStmt.accept(BlockStmt.java:108)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:409)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:413)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitChildFromParent(ReductionOpportunitiesBase.java:199)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitForStmt(StandardVisitor.java:268)
	at com.graphicsfuzz.common.typing.ScopeTrackingVisitor.visitForStmt(ScopeTrackingVisitor.java:93)
	at com.graphicsfuzz.common.ast.stmt.ForStmt.accept(ForStmt.java:57)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitBlockStmt(ReductionOpportunitiesBase.java:119)
	at com.graphicsfuzz.common.ast.stmt.BlockStmt.accept(BlockStmt.java:108)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.common.typing.ScopeTrackingVisitor.visitFunctionDefinition(ScopeTrackingVisitor.java:110)
	at com.graphicsfuzz.reducer.reductionopportunities.ReductionOpportunitiesBase.visitFunctionDefinition(ReductionOpportunitiesBase.java:83)
	at com.graphicsfuzz.common.ast.decl.FunctionDefinition.accept(FunctionDefinition.java:42)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitChildFromParent(StandardVisitor.java:409)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visitTranslationUnit(StandardVisitor.java:112)
	at com.graphicsfuzz.common.ast.TranslationUnit.accept(TranslationUnit.java:123)
	at com.graphicsfuzz.common.ast.visitors.StandardVisitor.visit(StandardVisitor.java:97)
	at com.graphicsfuzz.reducer.reductionopportunities.ExprToConstantReductionOpportunities.findOpportunitiesForShader(ExprToConstantReductionOpportunities.java:62)
	at com.graphicsfuzz.reducer.reductionopportunities.ExprToConstantReductionOpportunities.lambda$findOpportunities$0(ExprToConstantReductionOpportunities.java:53)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1494)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:486)
	at com.graphicsfuzz.reducer.reductionopportunities.ExprToConstantReductionOpportunities.findOpportunities(ExprToConstantReductionOpportunities.java:54)
	at com.graphicsfuzz.reducer.reductionopportunities.IReductionOpportunityFinder$5.findOpportunities(IReductionOpportunityFinder.java:100)
	at com.graphicsfuzz.reducer.glslreducers.SystematicReductionPass.tryApplyReduction(SystematicReductionPass.java:57)
	at com.graphicsfuzz.reducer.glslreducers.SystematicReductionPassManager.applyReduction(SystematicReductionPassManager.java:69)
	at com.graphicsfuzz.reducer.ReductionDriver.doReduction(ReductionDriver.java:178)
	at com.graphicsfuzz.reducer.tool.GlslReduce.doReductionHelper(GlslReduce.java:527)
	at com.graphicsfuzz.reducer.tool.GlslReduce.mainHelper(GlslReduce.java:453)
	at com.graphicsfuzz.reducer.tool.GlslReduce.main(GlslReduce.java:224)

**Comment by afd** [comment]
Fixed via #727.
