### ISSUE TITLE
gfauto exited due to reports/fuzz_failures not existing

### ISSUE THREAD

**Issue by afd** [google/graphicsfuzz#756]
Example output:

Iteration seed: 86881462316368165127192679234098336963134139042781135795395558918944225640553
Exec:['/data/afd-SPIRV-Tools/cmake-build-debug/tools/spirv-fuzz', 'temp/1995ef2c/source_template/reference/shader.frag.spv', '-o', 'temp/1995ef2c/source_template/variant/shader.frag.spv', '--seed=2840756186']
Command failed: ['/data/afd-SPIRV-Tools/cmake-build-debug/tools/spirv-fuzz', 'temp/1995ef2c/source_template/reference/shader.frag.spv', '-o', 'temp/1995ef2c/source_template/variant/shader.frag.spv', '--seed=2840756186']
RETURNCODE: -6
STDOUT:

STDERR:
spirv-fuzz: /data/afd-SPIRV-Tools/source/opt/instruction.h:502: const spvtools::opt::Operand& spvtools::opt::Instruction::GetOperand(uint32_t) const: Assertion `index < operands_.size() && "operand index out of bound"' failed.

Traceback (most recent call last):
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz_spirv_test.py", line 157, in fuzz_spirv
    seed=str(random.getrandbits(spirv_fuzz_util.GENERATE_SEED_BITS)),
  File "/data/graphicsfuzz/gfauto/gfauto/spirv_fuzz_util.py", line 98, in run_generate_on_shader_job
    other_args,
  File "/data/graphicsfuzz/gfauto/gfauto/spirv_fuzz_util.py", line 58, in run_generate
    subprocess_util.run(cmd)
  File "/data/graphicsfuzz/gfauto/gfauto/subprocess_util.py", line 150, in run
    raise ex
  File "/data/graphicsfuzz/gfauto/gfauto/subprocess_util.py", line 140, in run
    result = run_helper(cmd, check_exit_code, timeout, env, working_dir)
  File "/data/graphicsfuzz/gfauto/gfauto/subprocess_util.py", line 126, in run_helper
    raise subprocess.CalledProcessError(exit_code, process.args, stdout, stderr)
subprocess.CalledProcessError: Command '['/data/afd-SPIRV-Tools/cmake-build-debug/tools/spirv-fuzz', 'temp/1995ef2c/source_template/reference/shader.frag.spv', '-o', 'temp/1995ef2c/source_template/variant/shader.frag.spv', '--seed=2840756186']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/graphicsfuzz/gfauto/.venv/bin/gfauto_fuzz", line 11, in <module>
    load_entry_point('gfauto', 'console_scripts', 'gfauto_fuzz')()
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz.py", line 162, in main
    main_helper(settings_path, iteration_seed, skip_writing_binary_recipes)
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz.py", line 267, in main_helper
    binary_manager,
  File "/data/graphicsfuzz/gfauto/gfauto/fuzz_spirv_test.py", line 160, in fuzz_spirv
    if len(list(fuzz_failures_dir.iterdir())) < settings.maximum_fuzz_failures:
  File "/usr/lib/python3.6/pathlib.py", line 1081, in iterdir
    for name in self._accessor.listdir(self):
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: 'reports/fuzz_failures'

**Comment by paulthomson** [comment]
Fixed in #761
